Feature/arrays
formindev/study pull request #1
Opened 2019-10-05 15:20 UTC by formindev

Arrays exercise finished

2019-10-14 21:11 UTC, artempartos requested changes

2019-10-14 21:11 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        array.each { |item| max = item if max < item }
давай выделим отдельно функциию поиска максимального значения

2019-10-15 14:03 UTC, formindev reviewed
Added max function to replace method

2019-11-14 09:32 UTC, Andrew8xx8 approved these changes

2019-11-25 15:46 UTC, merged