Feature/fp
formindev/study pull request #2
Opened 2019-10-07 08:43 UTC by formindev

Fp execise finished

2019-10-14 21:12 UTC, artempartos requested changes

2019-10-14 21:12 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        max = 0
код из другого PR

2019-10-15 14:13 UTC, formindev reviewed
Remove unnecessary code

2019-11-14 09:33 UTC, Andrew8xx8 approved these changes

2019-11-25 16:21 UTC, merged