Feature/fp2
formindev/study pull request #3
Opened 2019-10-15 16:46 UTC by formindev

Fp2 exercise finished

2019-11-14 09:36 UTC, Andrew8xx8 requested changes

2019-11-14 09:36 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        my_map { |item| return_array << item unless item.nil? }
Может быть `if item.present?`. Условия `если не` воспринимаются сложнее чем просто `если`.

2019-11-14 12:04 UTC, formindev commented on test/exercise/fp2/solution.rb
> +        my_map { |item| return_array << item unless item.nil? }
К сожалению: "present is a method provided by ActiveSupport. It is not a part of core ruby."

2019-11-15 12:54 UTC, artempartos commented on test/exercise/fp2/solution.rb
> +        my_map { |item| return_array << item unless item.nil? }
да, все верно, рельс то тут нет )

2019-11-15 12:54 UTC, artempartos commented
👍

2019-11-25 16:24 UTC, merged